### ISSUE TITLE
Local pyWars Update Feasibility

### ISSUE THREAD

**Issue by jus0xA** [MarkBaggett/pyWars#1]
@MarkBaggett I previously took SEC573 back in 2018 and have the offline pyWars server on my VM.  Is there anyway to update my copy of pyWars with the most up to date version, or would that require purchasing the course again?  Thanks!

**Comment by MarkBaggett** [comment]
Hi Justin
We only distribute the labs update with the new course material.  You can register to retake any SANS course at 50% off with discount code ALUMNI.  That said send me an email at mbaggett@sans.org and let me know what version of the course you took.  I’ll let you know what has changed. While the course material has been completely rewritten to the use the newest versions of Python, visual studio code as a debugger and editor, and a many other updates there are probably fewer than 20 new pywars labs. (Other than adjustments made to accommodate new python modules and best practices. )

Mark

**Comment by jus0xA** [comment]
Thank you for your assistance, Mark.  It seems there has been a good bit of updates made to the course since I last took it.
